# Generated by Django 5.1 on 2024-11-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'tbl_ServiceCategory',
            },
        ),
    ]
