# Generated by Django 5.1 on 2024-11-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='Description',
            field=models.TextField(default='NA'),
        ),
    ]
