# Generated by Django 5.1 on 2024-12-06 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_servicecategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('cs_id', models.AutoField(primary_key=True, serialize=False)),
                ('CaseStudyName', models.CharField(blank=True, max_length=300, null=True)),
                ('Description', models.TextField(default='NA')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.servicecategory')),
            ],
            options={
                'db_table': 'tbl_CaseStudy',
            },
        ),
    ]
