# Generated by Django 5.1 on 2024-12-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_casestudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='Images',
            field=models.TextField(default='NA'),
        ),
    ]
