# Generated by Django 5.1 on 2024-12-06 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_casestudy_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insights',
            fields=[
                ('insight_id', models.AutoField(primary_key=True, serialize=False)),
                ('ServiceHeading', models.CharField(blank=True, max_length=300, null=True)),
                ('Description', models.TextField(default='NA')),
                ('Preview', models.CharField(blank=True, max_length=300, null=True)),
                ('Buy', models.CharField(blank=True, max_length=300, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.servicecategory')),
            ],
            options={
                'db_table': 'tbl_Insights',
            },
        ),
    ]
