# Generated by Django 4.1.3 on 2022-11-23 21:47

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('category_slug', models.CharField(max_length=250)),
                ('category_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_blog_categories',
            },
        ),
        migrations.CreateModel(
            name='BlogKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_name', models.CharField(blank=True, max_length=250, null=True)),
                ('keywords_slug', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'tbl_blog_keywords',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('shortDescription', models.TextField(max_length=300)),
                ('highLights', ckeditor.fields.RichTextField(default='')),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog')),
                ('viewCount', models.IntegerField(default=0)),
                ('shareCount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pub', 'Published'), ('daf', 'Draft'), ('trs', 'Trash')], default='pub', max_length=50)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now_add=True, null=True)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategorie')),
                ('keywords', models.ManyToManyField(blank=True, default='', to='blog.blogkeyword')),
            ],
            options={
                'db_table': 'tbl_blogs',
            },
        ),
    ]
