# Generated by Django 5.1 on 2024-09-03 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogs",
            options={"managed": False},
        ),
    ]
