# Generated by Django 5.1 on 2024-09-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blogs_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="blog_pdfs/"),
        ),
    ]
