# Generated by Django 5.1 on 2024-09-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_blogs_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="image",
            field=models.ImageField(upload_to="blog_images/"),
        ),
    ]
