# Generated by Django 4.1.3 on 2022-11-23 21:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('details', models.TextField(max_length=250)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('details', models.TextField(max_length=250)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=250)),
                ('bio', models.TextField(blank=True, null=True)),
                ('career', models.ManyToManyField(blank=True, default='', to='publications.authorcareer')),
                ('education', models.ManyToManyField(blank=True, default='', to='publications.authoreducation')),
            ],
            options={
                'db_table': 'tbl_publication_authors',
            },
        ),
        migrations.CreateModel(
            name='PublicationCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('category_slug', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'tbl_publication_categories',
            },
        ),
        migrations.CreateModel(
            name='TableOfContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=250)),
                ('pages', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('contentFile', models.FileField(default='#', upload_to='publications/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
            options={
                'db_table': 'tbl_publication_toc',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('heading', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(upload_to='publication_image')),
                ('highResCover', models.ImageField(blank=True, null=True, upload_to='publication_image')),
                ('publishYear', models.IntegerField()),
                ('shortDescription', models.TextField(blank=True, max_length=300, null=True)),
                ('longDescripton', models.TextField(blank=True, null=True)),
                ('aboutTextbook', models.TextField(blank=True, null=True)),
                ('aboutAuthors', models.TextField(blank=True, null=True)),
                ('priceHardCover', models.IntegerField()),
                ('priceEbook', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('ebookFile', models.FileField(default='', upload_to='publications/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('bookSubtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('copyrights', models.CharField(blank=True, max_length=300, null=True)),
                ('publisher', models.CharField(blank=True, max_length=300, null=True)),
                ('copyrightHolder', models.CharField(blank=True, max_length=300, null=True)),
                ('DOI', models.CharField(blank=True, max_length=300, null=True)),
                ('softcoverISBN', models.CharField(blank=True, max_length=300, null=True)),
                ('editionNumber', models.CharField(blank=True, max_length=300, null=True)),
                ('numberOfPages', models.IntegerField()),
                ('numberOfIllustration', models.IntegerField()),
                ('topics', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('pub', 'Published'), ('daf', 'Draft'), ('trs', 'Trash')], default='pub', max_length=50)),
                ('lastUpdated', models.DateTimeField(auto_now_add=True, null=True)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.bookauthor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publicationcategorie')),
                ('tableofContents', models.ManyToManyField(blank=True, default='', to='publications.tableofcontent')),
            ],
            options={
                'db_table': 'tbl_publication',
            },
        ),
    ]
