# Generated by Django 5.1 on 2024-09-03 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tableofcontent",
            options={"managed": False},
        ),
    ]
