# Generated by Django 5.1 on 2024-09-03 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0002_alter_tableofcontent_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tableofcontent",
            options={},
        ),
    ]
