# Generated by Django 4.1.3 on 2022-11-23 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphabet', models.CharField(max_length=1)),
                ('color', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_color_lists',
            },
        ),
        migrations.CreateModel(
            name='Inoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=150)),
                ('order_number', models.CharField(blank=True, max_length=150, null=True)),
                ('due_date', models.DateField()),
                ('cratedAt', models.DateField(auto_now_add=True)),
                ('discounts', models.IntegerField(default=0)),
                ('taxes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_crm_invoices',
            },
        ),
        migrations.CreateModel(
            name='receiptInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_name', models.CharField(max_length=400)),
                ('company_name', models.CharField(blank=True, max_length=400, null=True)),
                ('street_address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=400)),
                ('receipt_zip', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'tbl_crm_invoice_receipt',
            },
        ),
        migrations.CreateModel(
            name='senderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=400)),
                ('street_address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=400)),
                ('sender_zip', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
                ('company_website', models.CharField(blank=True, max_length=400, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='crm/sender')),
            ],
            options={
                'db_table': 'tbl_crm_invoice_senders',
            },
        ),
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=400)),
                ('message', models.TextField(blank=True, null=True)),
                ('to_email', models.CharField(max_length=300)),
                ('cratedAt', models.DateTimeField(auto_now_add=True)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.contactus')),
            ],
            options={
                'db_table': 'tbl_crm_sent_message',
            },
        ),
        migrations.CreateModel(
            name='invoice_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('qty', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('amount', models.FloatField()),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.inoice')),
            ],
            options={
                'db_table': 'tbl_crm_invoices_items',
            },
        ),
        migrations.AddField(
            model_name='inoice',
            name='invoice_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.receiptinfo'),
        ),
        migrations.AddField(
            model_name='inoice',
            name='invoice_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.senderinfo'),
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.contactus')),
            ],
            options={
                'db_table': 'tbl_crm_activities',
            },
        ),
    ]
