# Generated by Django 5.1 on 2024-09-03 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"managed": False},
        ),
    ]
