# Generated by Django 5.1 on 2024-09-03 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_cart_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={},
        ),
    ]
